version: '3.8'

services:
  app:
    image: caregiver_app:latest
    container_name: caregiver_app
    build: .
    ports:
      - '${PORT}:${DOCKER_PORT}'
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - caregiver_network

  db:
    image: postgres:14-alpine
    # container_name: caregiver_db
    restart: always
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: 5434
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - caregiver_network
    expose:
      - 5434
volumes:
  db-data:
networks:
  caregiver_network:
    driver: bridge
